M48
; DRILL file {KiCad 9.0.6} date 2025-11-22T08:39:34-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-22T08:39:34-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.3331Y-0.5982
X1.5606Y-0.5982
T2
X1.2717Y-3.06
M30
