M48
; DRILL file {KiCad 9.0.6} date 2026-03-31T07:19:29-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-31T07:19:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1181
%
G90
G05
T2
X-0.2969Y1.3402
T3
X1.002Y1.9931
T4
X1.7894Y1.9931
T5
X1.9331Y2.0374
X1.9331Y0.1476
T6
X1.9331Y2.0374
X1.9331Y0.1476
T1
G00X-0.0098Y1.3402
M15
G01X0.0067Y1.3402
M16
G05
M30
