#!/usr/bin/env python3
"""Generate event type definitions for Python and TypeScript from C++ headers.

Firmware C++ enums are the source of truth. This script parses the enums listed
in SOURCES and emits:
  - api/event_types.py                     (IntEnum classes + name map)
  - dashboard/src/generated/eventTypes.ts  (const objects + name map)

Run manually after editing either header, or via the pre-commit hook.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# (header path relative to repo root, enum name, prefix to strip from display names)
SOURCES = [
    ("src/util/event_record.h", "EventType", ""),
    ("src/lora/message.h", "EventCode", "EVENT_"),
]

GENERATED_NOTICE = "DO NOT EDIT - generated by tools/gen_event_types.py from C++ headers"


def parse_enum(header_path: Path, enum_name: str) -> list[tuple[str, int]]:
    """Return [(member_name, value), ...] in source order for the named enum."""
    text = header_path.read_text()
    # Matches `enum EventCode {` and `enum class EventType : uint8_t {`.
    pattern = rf"enum(?:\s+class)?\s+{re.escape(enum_name)}[^{{]*\{{([^}}]+)\}}"
    match = re.search(pattern, text)
    if not match:
        raise RuntimeError(f"Enum {enum_name} not found in {header_path}")

    entries: list[tuple[str, int]] = []
    for raw_line in match.group(1).splitlines():
        line = raw_line.split("//")[0].strip()
        if not line:
            continue
        m = re.match(r"(\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+)\s*,?", line)
        if m:
            entries.append((m.group(1), int(m.group(2), 0)))
    return entries


def to_display_name(member: str, strip_prefix: str) -> str:
    """Convert SCHEDULE_APPLIED -> 'Schedule Applied', stripping an optional prefix."""
    if strip_prefix and member.startswith(strip_prefix):
        member = member[len(strip_prefix):]
    return " ".join(part.capitalize() for part in member.split("_"))


def hex_literal(value: int) -> str:
    """Emit 0xNN for 1-byte values, 0xNNNN for wider values."""
    width = 2 if value <= 0xFF else 4
    return f"0x{value:0{width}X}"


def emit_python(enums: list[tuple[str, str, list[tuple[str, int]]]], out_path: Path) -> None:
    lines = [
        f'"""{GENERATED_NOTICE}"""',
        "",
        "from enum import IntEnum",
        "",
    ]
    for enum_name, _strip, entries in enums:
        lines.append("")
        lines.append(f"class {enum_name}(IntEnum):")
        for member, value in entries:
            lines.append(f"    {member} = {hex_literal(value)}")
        lines.append("")

    lines.append("")
    lines.append("EVENT_CODE_NAMES: dict[int, str] = {")
    for _enum_name, strip, entries in enums:
        for member, value in entries:
            lines.append(f'    {hex_literal(value)}: "{to_display_name(member, strip)}",')
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines))


def emit_typescript(enums: list[tuple[str, str, list[tuple[str, int]]]], out_path: Path) -> None:
    lines = [
        f"// {GENERATED_NOTICE}",
        "",
    ]
    for enum_name, _strip, entries in enums:
        lines.append(f"export const {enum_name} = {{")
        for member, value in entries:
            lines.append(f"  {member}: {hex_literal(value)},")
        lines.append("} as const;")
        lines.append("")

    lines.append("export const EVENT_CODE_NAMES: Record<number, string> = {")
    for _enum_name, strip, entries in enums:
        for member, value in entries:
            lines.append(f"  {hex_literal(value)}: '{to_display_name(member, strip)}',")
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines))


def main() -> int:
    parsed: list[tuple[str, str, list[tuple[str, int]]]] = []
    for rel_path, enum_name, strip in SOURCES:
        header = REPO_ROOT / rel_path
        parsed.append((enum_name, strip, parse_enum(header, enum_name)))

    py_out = REPO_ROOT / "api" / "event_types.py"
    ts_out = REPO_ROOT / "dashboard" / "src" / "generated" / "eventTypes.ts"
    ts_out.parent.mkdir(parents=True, exist_ok=True)

    emit_python(parsed, py_out)
    emit_typescript(parsed, ts_out)

    print(f"Generated {py_out.relative_to(REPO_ROOT)}")
    print(f"Generated {ts_out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
