M48
; DRILL file {KiCad 9.0.6} date 2025-12-18T05:42:00-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-18T05:42:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.4394Y-0.7392
X1.6669Y-0.7392
T2
X1.5945Y-3.0591
M30
