M48
; DRILL file {KiCad 9.0.6} date 2026-03-03T14:06:12-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-03T14:06:12-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X1.935Y-0.6378
T1
G00X1.648Y-0.6378
M15
G01X1.6315Y-0.6378
M16
G05
M30
